import { getDashboard } from "@/lib/dashboard";
import type { PersonView } from "@/lib/types";
import { MetricCharts } from "./components/MetricCharts";
import { ScoreHero } from "./components/ScoreHero";
import { RecoveryTrend } from "./components/RecoveryTrend";
import { PersonTabs } from "./components/PersonTabs";

// Read-only, server-rendered shell. Reads cached summaries + insights from
// Postgres — it never calls Claude, so it's fast and free on every load. The
// interactive charts hydrate on the client.
export const dynamic = "force-dynamic";

function PersonSection({ p }: { p: PersonView }) {
  const by =
    p.insight?.generatedBy === "claude" ? `Claude · ${p.insight.model ?? ""}` : "rules · free";
  return (
    <section className="person">
      <div className="person-head">
        <h2>{p.name}</h2>
        {p.periodEnd && <span className="period">week ending {p.periodEnd}</span>}
      </div>

      {p.scores.latest && <ScoreHero s={p.scores.latest} />}
      {p.scores.history.length > 1 && <RecoveryTrend history={p.scores.history} />}

      {p.insight && (
        <div className="insight">
          <div className="insight-top">
            <h3>{p.insight.headline}</h3>
            <span className="by">{by}</span>
          </div>
          <p className="summary">{p.insight.summary}</p>

          {p.insight.observations.length > 0 && (
            <>
              <div className="obs-label">What stood out</div>
              <ul>
                {p.insight.observations.map((o, i) => (
                  <li key={i}>{o}</li>
                ))}
              </ul>
            </>
          )}

          {p.insight.watch_items.length > 0 && (
            <>
              <div className="watch-label">Worth watching</div>
              <ul>
                {p.insight.watch_items.map((o, i) => (
                  <li key={i}>{o}</li>
                ))}
              </ul>
            </>
          )}

          {p.insight.encouragement && <p className="encourage">{p.insight.encouragement}</p>}
        </div>
      )}

      <div className="section-title vitals-title">Vitals</div>
      <MetricCharts metrics={p.metrics} />
    </section>
  );
}

export default async function Home() {
  let people: PersonView[] = [];
  let error: string | null = null;
  try {
    people = await getDashboard();
  } catch (err) {
    error = (err as Error).message;
  }

  return (
    <>
      <header className="app-header">
        <div className="wrap">
          <p className="eyebrow">Fitmore · M3 (mock data)</p>
          <h1>Personal health intelligence</h1>
          <p className="sub">
            Recovery, strain &amp; sleep scores computed from synthetic Fitbit Air data — plus a weekly readout.
          </p>
        </div>
      </header>

      <main>
        <div className="wrap">
          {error ? (
            <div className="empty">
              <strong>Couldn&apos;t reach the database.</strong>
              <p>
                Start Postgres and run the pipeline, then reload:
                <br />
                <code>npm run db:up</code> · <code>npm run pipeline</code>
              </p>
              <p style={{ fontSize: 12, opacity: 0.7 }}>({error})</p>
            </div>
          ) : people.length === 0 ? (
            <div className="empty">
              <strong>No data yet.</strong>
              <p>
                Populate it with the mock pipeline: <code>npm run pipeline</code>, then reload.
              </p>
            </div>
          ) : (
            <>
              <PersonTabs
                tabs={people.map((p) => ({
                  id: p.id,
                  name: p.name,
                  worstFlag: p.worstFlag,
                  cardiac: p.isCardiacPatient,
                }))}
              >
                {people.map((p) => (
                  <PersonSection key={p.id} p={p} />
                ))}
              </PersonTabs>

              <div className="safety">
                <span className="badge-text">Cardiac care</span>
                <p>
                  This is tracking and decision-support, <strong>not diagnosis</strong>. Flags are a
                  prompt to talk to a cardiologist — never a conclusion. Blood pressure, when added,
                  will come only from a validated cuff device (Huawei Watch D2), never an optical
                  estimate.
                </p>
              </div>

              <footer className="meta">
                Data is synthetic. Insights{" "}
                {people[0]?.insight?.generatedBy === "claude"
                  ? "written by Claude"
                  : "generated by the rules engine (no API key set — $0)"}
                . Shaded band on each chart is that metric&apos;s personal usual range (baseline ± 2 SD).
              </footer>
            </>
          )}
        </div>
      </main>
    </>
  );
}
